// All player-visible text. Switching language is a data change, never a code change.
// Languages: ru (primary Yandex audience) + en fallback.

export const STRINGS = {
  en: {
    title: 'STACK',
    tap_to_play: 'Tap to play',
    play: 'Play',
    daily: 'Daily',
    daily_challenge: 'Daily Challenge',
    score: 'Score',
    best: 'Best',
    coins: 'Coins',
    streak: 'Streak',
    day: 'day',
    days: 'days',
    perfect: 'PERFECT!',
    combo: 'Combo',
    game_over: 'Game Over',
    new_best: 'New Best!',
    revive: 'Revive',
    revive_sub: 'Watch ad → continue this run',
    double_coins: 'Double coins',
    double_sub: 'Watch ad → ×2 coins',
    restart: 'Restart',
    home: 'Home',
    leaderboard: 'Leaderboard',
    themes: 'Themes',
    locked: 'Locked',
    unlock_for: 'Unlock for',
    sound_on: 'Sound: on',
    sound_off: 'Sound: off',
    paused: 'Paused',
    resume: 'Resume',
    today_best: "Today's best",
    daily_done: "You played today. Come back tomorrow!",
    streak_bonus: 'Streak bonus',
    height: 'Height',
    tap_hint: 'Tap / Space to drop',
    loading: 'Loading…',
    close: 'Close',
    sign_in_lb: 'Sign in to Yandex to see the leaderboard',
    you: 'You',
  },
  ru: {
    title: 'STACK',
    tap_to_play: 'Нажми, чтобы играть',
    play: 'Играть',
    daily: 'Дейли',
    daily_challenge: 'Задание дня',
    score: 'Счёт',
    best: 'Рекорд',
    coins: 'Монеты',
    streak: 'Серия',
    day: 'день',
    days: 'дн.',
    perfect: 'ИДЕАЛЬНО!',
    combo: 'Комбо',
    game_over: 'Игра окончена',
    new_best: 'Новый рекорд!',
    revive: 'Продолжить',
    revive_sub: 'Смотреть рекламу → продолжить',
    double_coins: 'Удвоить монеты',
    double_sub: 'Смотреть рекламу → ×2 монеты',
    restart: 'Заново',
    home: 'Домой',
    leaderboard: 'Таблица лидеров',
    themes: 'Скины',
    locked: 'Закрыто',
    unlock_for: 'Открыть за',
    sound_on: 'Звук: вкл',
    sound_off: 'Звук: выкл',
    paused: 'Пауза',
    resume: 'Продолжить',
    today_best: 'Сегодня лучший',
    daily_done: 'Вы сыграли сегодня. Возвращайтесь завтра!',
    streak_bonus: 'Бонус за серию',
    height: 'Высота',
    tap_hint: 'Нажми / Space — сбросить',
    loading: 'Загрузка…',
    close: 'Закрыть',
    sign_in_lb: 'Войдите в Яндекс, чтобы увидеть таблицу лидеров',
    you: 'Вы',
  },
};
